# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, jun-1-CI/CD-Grunt-Explore]
  pull_request:
    branches: [ main, ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: JSDoc - Generate Documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir:  ./source/scripts
          recurse: true
          output_dir:  ./docs

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: npm install

      - name: Run linters
        run: npm run lint
     
      - name: Run Jest Tests
        run: npm run test

      - name: Create Coverage
        run: node ./node_modules/jest/bin/jest.js --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Node Server
        run: nohup npm run host &

      - name: Run Cypress Tests
        run: npm run cypress

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
